service: api-server
# app and org for use with dashboard.serverless.com
app: food-suggest
org: gunasekhar

plugins:
 - serverless-python-requirements
 
provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  memorySize: 1536
  timeout: 60
  vpc:
    securityGroupIds:
      - sg-f19bbea2
    subnetIds:
      - subnet-b8e129f5
      - subnet-3ce21032
      - subnet-1dc7c033
      - subnet-9782bbf0
      - subnet-7d90dc43
      - subnet-f4c4c1a8
  
custom:
 pythonRequirements:
  slim : true  
  
functions:
  food-create:
    handler: src/food.create
    events:
      - http: 
          path: food
          method: POST
  food-findAll:
    handler: src/food.findAll
    events:
      - http: 
          path: food
          method: GET          
  food-findOne:
    handler: src/food.findOne
    events:
      - http: 
          path: food/{Id}
          method: GET 
  food-update:
    handler: src/food.update
    events:
      - http: 
          path: food
          method: PUT
  food-delete:
    handler: src/food.delete
    events:
      - http: 
          path: food
          method: DELETE             
  food-category-create:
    handler: src/food-category.create
    events:
      - http: 
          path: food-category
          method: POST
  food-category-findAll:
    handler: src/food-category.findAll
    events:
      - http: 
          path: food-category
          method: GET          
  food-category-findOne:
    handler: src/food-category.findOne
    events:
      - http: 
          path: food-category/{Id}
          method: GET 
  food-category-update:
    handler: src/food-category.update
    events:
      - http: 
          path: food-category
          method: PUT
  food-category-delete:
    handler: src/food-category.delete
    events:
      - http: 
          path: food-category
          method: DELETE 